# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  on:
  push:
    tags:
      - "*.*.*"
  
permissions:
  contents: read
  packages: write

jobs:
  build-windows:
    runs-on: windows-2025
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.5"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync

    - name: Build windows image
      run: flet build windows

    - name: show all folders
      run: Get-ChildItem -Path "./" -Recurse -Directory
      shell: pwsh

    - name: Upload artifacts.
      uses: actions/upload-artifact@v4
      with: 
        name: windows-build
        path: dist
